version: "3.3"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    networks:
      - webnet
    ports: 
      - "8883:8883"
networks:
  webnet: